### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by bor-lin** [jkbuha/XPS-9520-AlderLake-OpenCore#2]
Helo,
I have got some questions:
Should Monterey 12.6.6 install without any problems with your EFI/OC?
(I can't get 12.6.2).
Which bios version are you using?
(I don't have Intel SGX).
I managed to install it, but I don't have WiFi.
(regardless of whether CFG LOCK is disabled before or after installation)

Thank you in advance for your tips
Janusz

**Comment by jkbuha** [comment]
Monterey 12.6.x, 12.7 and Ventura all work.
Bios version is 1.6 (for undervolting) but all versions should work.

Wifi is not working because (a) it's currently disabled in the EFI folder config as I copied the actual kext over to /Library/Extensions and (b) you need to install the right kexts for Monterey (the latest git update has the ones for Ventura)

**Comment by bor-lin** [comment]
Thank you for the excellent software that allows  to use MacOs on the XPS 9520.
Thank you for the precise directions.
I still have very big problems with WiFi and there is no Windows-key + zoom.
Tests with version downloaded on November 4, 2023:
0. I changed the bios from 1.5 to 1.6 - just in case.
1. I installed 12.6.6 and 13.6.1 - there is no wifi.
2. I changed the config.plist so that itlwm.kext and AirportItlwm.kext 
were enabled - there is no WiFi.
2a. I used ProperTree for this - is it right?
3. I did setup_var CpuSetup 0x43 0x00 (not setup_var_cv) - is it correct?
4. I reinstalled 13.6.1 using the original config.plist.
5. I copied itlwm.kext and AirportItlwm.kext to /Library/Extension 
(and security enabled} - no WiFi.
6. so far I have booted from a pendrive in the right USB-C port.
Now I booted using the left port - there is WiFi.
7. I installed HoRNDIS-9.2 - it works. But from now on WiFi is not active.

From now on, there is no WiFi, regardless of whether you boot from 
the left or right port or from the nvme disk. 
WiFi operation seems random.
Maybe only one of itlwm.kext and AirportItlwm.kext should be used?
Any tip will be very important.

I have the 9520 version with a touch screen 3840 x 2400 (4K UHD+) 500 cd/m²
00:14.3 Network controller: Intel Corporation Alder Lake-P PCH CNVi WiFi (rev 01)

**Comment by jkbuha** [comment]
You cannot use both itlwm and airportltwm, just one of them. The quickest
and easiest way is to just enable itlwm (disable airportltwm) and then you
have to install the Heliport app to use wifi. You can find it here:
https://github.com/OpenIntelWireless/HeliPort

**Comment by bor-lin** [comment]
simply remove AirportItlwm.kext  from /Library/Extensions ?
no kextutil or so ?

**Comment by jkbuha** [comment]
remove airportltwm from /L/E and run sudo kextcache -i / before rebooting

don’t install itlwm in /L/E, use the usual OC/Kexts folder and enable it from config.plist

**Comment by bor-lin** [comment]
In place of one of the installed montereys, I installed ventura. 
Opencore calls it monterey (in boot time). What to do?
Is CleanNvram safe for other systems (grub, windows, bootable by efibootmgr)?
Won't CleanNvram destroy variables not created by Opencore?

**Comment by jkbuha** [comment]
I don’t know (it sounds cosmetic anyway as it’s just the partition name,
which OC correctly boots anyway) but I’m assuming you’ve now solved the
WiFi problem?

**Comment by bor-lin** [comment]
WiFi now ok (twice by L/E ones by kext).
Not cosmetic - I have many systems.
I would like to try CleanNvram but who knows what would be.

**Comment by jkbuha** [comment]
I’ve never used cleannvram so not sure. But would try and create a separate
boot entry for all the other macOS partitions if that’s the case

**Comment by bor-lin** [comment]
I have it, but I'm afraid that after CleanNvram I may not have it.
After changing OC, what is the best way to update config.plist?
(I use ProperTree in Gentoo, but it's strange, the configs are about twice as small. But it seems to work)

**Comment by bor-lin** [comment]
CleanNvram removed all bootable variables (Grub, efibootmgr, emulation, Windows, ..)
Of the 309 variables in nvram, he left 273.
By the way, what is the nvram capacity in the XPS 9520?
He left one openchrome from which he intends to start.
This is where I interrupted him and recreated all  lost systems.
Windows made its own second variable.
I don't know yet if it will help to change the names ventura -> monterey.

**Comment by jkbuha** [comment]
For me it changed when I updated macos.
