### ISSUE TITLE
Magnificent Hackintosh..

### ISSUE THREAD

**Issue by Baio1977** [jkbuha/XPS-9520-AlderLake-OpenCore#3]
I am a fan of the Hackintosh world, could you leave me Extracted files with EFI debug (better if coming from updated Bios latest version) + ioreg log????
Thank you 1000.
Maybe after reading ACPI I can also help you make slep\wake work better.

**Comment by jkbuha** [comment]
Prego.

My config is a bit unorthodox as I’m using an eGPU setup (via TB, HDMI out
to monitor) for display (as alderlake iGPU not supported). Machine
successfully sleeps and wakes (I can ssh into it), eGPU fires up but
display doesn’t switch on.

Happy to also consider hibernatemode 25 if easier, but neither work
properly for now.

Will send you files via pm.
