### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by bjack12001** [jkbuha/XPS-9520-AlderLake-OpenCore#6]
Hi,

Its really good to see a hackintosh for a 12 gen intel processor, I have a HP Victus 12th gen processor, and i'm trying to use your EFI folder, however, its just not booting up. Can you please give me the "BOOT" folder that falls under the EFI folder. Currently your EFI folder only has the OC folder, and I think we need the "BOOT" folder as well for it to work.

Thanks.

**Comment by jkbuha** [comment]
I dont have a BOOT folder as I just point the UEFI Bios to directly load opencore.efi. Presumably you can do the same with your HP. Failing that, just download the original OC 0.9.9 pkg from github and manually unpack the BOOTx64.efi to the BOOT folder.

**Comment by bjack12001** [comment]
Hi,

Thank you for your reply, and direction, I did try your suggestion and extracted the BOOTx64.efi from the OC 0.9.9 pkg into the BOOT folder, however when I try to click on the install Ventura option it gets stuck at a black screen with some lines of code, Attached is the screenshot of the screen it gets stuck on.

Can you please help me diagnose, i really want to get mac installed on this new machine i got.

Thank you for all your help.
![20240329_021617](https://github.com/jkbuha/XPS-9520-AlderLake-OpenCore/assets/57179602/c338abc0-ea2c-4220-841c-ffc2196a9666)

**Comment by jkbuha** [comment]
That’s because this EFI is not configured or suitable for an HP laptop, and
can’t help you any further unfortunately. Suggest you get some help on
Reddit or tonymac from someone who is directly experienced with your
machine.

Best of luck!

**Comment by bjack12001** [comment]
ok ... thank you
